-- MySQL Script generated by MySQL Workbench
-- 03/28/15 10:20:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema provider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema provider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `provider` DEFAULT CHARACTER SET utf8 ;
USE `provider` ;

-- -----------------------------------------------------
-- Table `provider`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provider`.`admins` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(100) NOT NULL,
  `Last_name` VARCHAR(100) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `phone_number` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `provider`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provider`.`service` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NULL DEFAULT NULL,
  `Price` DOUBLE NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `provider`.`tariff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provider`.`tariff` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NULL DEFAULT NULL,
  `Price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `provider`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provider`.`users` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(100) NOT NULL,
  `Last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `balans` DOUBLE NULL DEFAULT '0',
  `status` VARCHAR(45) NOT NULL DEFAULT 'disabled',
  `birthday` DATE NOT NULL,
  `phone_number` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `id_tariff` INT(11) NOT NULL DEFAULT '1',
  `MAC` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `T_ID_idx` (`id_tariff` ASC),
  INDEX `M_ID_idx` (`MAC` ASC),
  CONSTRAINT `T_ID`
    FOREIGN KEY (`id_tariff`)
    REFERENCES `provider`.`tariff` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `provider`.`user_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provider`.`user_service` (
  `ID_order` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_user` INT(11) NOT NULL,
  `ID_service` INT(11) NOT NULL,
  `Status` VARCHAR(45) NOT NULL DEFAULT 'not done',
  PRIMARY KEY (`ID_order`),
  INDEX `ID_usl_idx` (`ID_service` ASC),
  INDEX `ID_user_idx` (`ID_user` ASC),
  CONSTRAINT `ID_user`
    FOREIGN KEY (`ID_user`)
    REFERENCES `provider`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID_usl`
    FOREIGN KEY (`ID_service`)
    REFERENCES `provider`.`service` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `admins` WRITE;
/*!40000 ALTER TABLE `admins` DISABLE KEYS */;
INSERT INTO `admins` VALUES (4,'Test','Test','admin','5f4dcc3b5aa765d61d8327deb882cf99','hjgjh@ya.ru','5646546');
/*!40000 ALTER TABLE `admins` ENABLE KEYS */;
UNLOCK TABLES;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
